### ISSUE TITLE
[Multiple issues] [UI] Fav button and line break + [UI?] Crash on reply's img loading

### ISSUE THREAD

**Issue by BreadlyUwU** [drasticactions/WinMasto#1]
**1.** WinMasto doens't show the "fav" button unless the user click on the object. (see screenshot #1 above)

**2.** He doens't interpret either line break (see the arrows i've insered on the screenshot #1)

**3.** Too much blue for the "dark theme", links are visible only if the background are "bright", I suggest an another color or just render a "light blue" that will visible everytime. (see screenshot #2)

**4.** When you access on an answer relied at a toot that contain an image, click on the img and WinMasto will crash. No problem with another images. (screenshot #2)

**Screen #1** 
![captureissueanon](https://cloud.githubusercontent.com/assets/28685939/26033451/eb7aa940-38ac-11e7-94a3-54269a372328.PNG)

**Screen #2**
![captureissue](https://cloud.githubusercontent.com/assets/28685939/26033585/87c2d5be-38af-11e7-9583-06348eda76bd.PNG)

(I'm sorry for the english not good as maternal language and that's my first issue report on Github and I don't know if I'm doing right, if some details are missings, just tell)

_(Meanwhile, congrats and thanks for the client, it's great to see that some Mastodon clients are comming on the Windows 10's store and this one have a good potential as a native client. With some work and patience it will probably become a must have for Win10 users who use Mastodon, so "never give up, trust your instinct!")_

**Comment by drasticactions** [comment]
First, thanks for the screenshots! Always helpful when someone exactly states what's wrong. 👍 

Clicking on the Status Images caused a crash because I wasn't casting the grid to the right property, nor handling it being null in the first place. It should be fixed with 021d9cc06dc3231ad1c8bf2106818dcf863b5d27.

For new lines in statuses, I'll take a look. The API returns all statuses as HTML, which I have to strip. I'll have to check for new lines and turn them into actual new lines.

And I can tweak the color of links for the light and dark theme.

**Comment by drasticactions** [comment]
Newlines fixed with 50a281b7ce9b8faa00d5ddaef61d6f37421e4ba2

**Comment by drasticactions** [comment]
Link colors fixed with 2c2ff6cd7d811293b9ea8718ad564c6e65a464ca

This is hard, because of the overriding of the theme that I'm doing. So for now, if you're on the light theme, they'll use the default accent color of white. If you're on the dark theme, I'll force it to be white so you'll be able to see the links.

I'll come back to this at some point.

**Comment by drasticactions** [comment]
Submitted https://github.com/drasticactions/WinMasto/releases/tag/1.8.3.0 to the store, closing this issue.
